name: Checkout and Setup Java and Gradle
description: "Checks out the context's branch, then sets up java and gradle."

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
