name: CI / Build Multiplatform Application
run-name: 
on:
  workflow-dispatch:
    inputs:
      android:
        default: ""
      desktop:
        default: ""
      ios:
        default: ""
      browser:
        default: ""

jobs:
  build-common:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java
        with:
          distribution: temurin
          version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build 
        run: ./gradlew metadataCommonMainClasses
      - name: Cache Build
        uses: actions/cache/save@v4
        key: 
        path: |
          dependencies/cache/path
          **/build/**
  build-app-android:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java
        with:
          distribution: temurin
          version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Restore Build Cache
        uses: actions/cache/restore@v4
        key: 
        path: |
          dependencies/cache/path
          **/build/**
      - name: Build Platform
        run: ./gradlew

  build-app-ios:
    runs-on: macos-14
    
  build-app-desktop:
    runs-on: ubuntu-latest
    
  build-app-browser:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/checkout-java-gradle
      - name: Build App
