name: Checkout and Setup Java and Gradle

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
